### ISSUE TITLE
ブログ記事をマークダウンで管理できるようにする

### ISSUE THREAD

**Issue by Solenoidal** [Solenoidal/connecting_the_dots#1]
## 動機
HeadlessCMSでブログコンテンツを配信しようと思ったが､CMSでの管理がそもそも面倒くさい｡マークダウン+Yaml front matterで書いてgithub管理したほうが投稿から配信までを一貫して行えると思う

## どうなってほしいのか

- [x] contents/blogディレクトリに記事を書いたマークダウンを配置する
- [x] ブログ情報(タイトル､投稿日､更新日､タグ､ヘッダー画像)を抽出したJSONファイルを作る
- [ ] ↓ コンポーネントを作る ↓
  - [x] 📜一覧表示用(CardList.vue)
  - [x] 🗂カード(Card.vue)
  - [ ] 記事本体(/blog/post/_slug.vueという形で配信)

**Comment by Solenoidal** [comment]
### DONE

- Card.vue, CardList.vue, blog.vueコンポーネントの作成
- モックのマークダウンファイルの配置
- マークダウンのメタ情報をコンポーネントに流す

### TODO

- スタイルの調整
- 詳細ページ
- アニメーション
- テスト
